"""empty message

Revision ID: 91a8628fc014
Revises: cfa309a30f46
Create Date: 2022-11-05 21:19:41.525357

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '91a8628fc014'
down_revision = 'cfa309a30f46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
