version: '3.9'

volumes:
  redis_volume_table:
  postgres_volume:

services:

  db_postgres_auth:
    image: postgres:13.3-alpine
    container_name: db_postgres_auth
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./scripts/postgresql:/docker-entrypoint-initdb.d
    env_file:
      - .env
    restart: always
    expose:
      - ${POSTGRES_PORT}
#    ports:
#      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    network_mode: "host"

  db_redis_table:
    image: 'redis:6.2.6'
    container_name: db_redis
    volumes:
      - redis_volume_table:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    network_mode: "host"